# wordpress/demo/values.yaml
wordpressUsername: admin
wordpressPassword: "p!mwb#p%L?n5#Kkq3DiJpboz"

service:
  type: ClusterIP

ingress:
  enabled: true
  hostname: "demo.kubeoptim.com.local"
  ingressClassName: traefik
  tls: false
  annotations: {}

replicaCount: 1
resources:
  requests: { cpu: 50m,  memory: 128Mi }
  limits:   { cpu: 200m, memory: 256Mi }

volumePermissions:
  enabled: true

persistence:
  enabled: true
  storageClass: longhorn-1r
  size: 2Gi

mariadb:
  enabled: true
  architecture: standalone
  auth:
    database: "bitnami_wordpress"
    username: "bn_wordpress"
    password: "w!T*oQ8eUPuWVc*JU#FfhfxZ"
    rootPassword: "S2EY?Y38kDH!R6%XDT?gXL@J"
  primary:
    persistence:
      enabled: true
      storageClass: longhorn-1r
      size: 2Gi
    resources:
      requests: { cpu: 50m,  memory: 128Mi }
      limits:   { cpu: 200m, memory: 256Mi }
  metrics:
    enabled: false
  volumePermissions:
    enabled: true

allowEmptyPassword: false
extraEnvVars:
  - name: ALLOW_EMPTY_PASSWORD
    value: "no"

metrics:
  enabled: false
