wordpressUsername: admin
wordpressPassword: "qY1JMwc1maOypFt6ItMU6s9j"
ingress:
  enabled: true
  hostname: "giroud.com"
  tls: true
  annotations:
    kubernetes.io/ingress.class: traefik
persistence:
  enabled: true
  storageClass: longhorn
  size: 10Gi
mariadb:
  primary:
    persistence:
      storageClass: longhorn
extraEnvVars:
  - name: REQUESTER_EMAIL
    value: "olivier@giroud.com"
  - name: REQUESTER_NAME
    value: "Olivier Giroud"
