# wordpress/makelele-sas/values.yaml
wordpressUsername: admin
wordpressPassword: "Fb6?DPHs!RYSxZN6qkyQcVDE"
image:
  registry: docker.io
  repository: bitnami/wordpress
  tag: "6.0.2-debian-11-r12"
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
ingress:
  enabled: true
  hostname: "makelele.com.local"
  ingressClassName: traefik
  tls: false
  annotations: {}
replicaCount: 1
resources:
  requests: { cpu: 50m,  memory: 128Mi }
  limits:   { cpu: 200m, memory: 256Mi }
volumePermissions:
  enabled: false
persistence:
  enabled: true
  storageClass: longhorn-1r
  size: 2Gi
mariadb:
  enabled: true
  architecture: standalone
  auth:
    database: "bitnami_wordpress"
    username: "bn_wordpress"
    password: "emPbgzQHqMixLydLH#VaNFCR"
    rootPassword: "E9hHxHbPpNNHxLHUsa?KynT?"
  primary:
    persistence:
      enabled: true
      storageClass: longhorn-1r
      size: 2Gi
    resources:
      requests: { cpu: 50m,  memory: 128Mi }
      limits:   { cpu: 200m, memory: 256Mi }
  metrics:
    enabled: false
  volumePermissions:
    enabled: false
allowEmptyPassword: false
extraEnvVars:
  - name: ALLOW_EMPTY_PASSWORD
    value: "no"
metrics:
  enabled: false
