# wordpress/leboeuf/values.yaml
wordpressUsername: admin
wordpressPassword: "#ft@eNJnxN8rfMn*ArF?@wfP"

service:
  type: ClusterIP

ingress:
  enabled: true
  hostname: "leboeuf.com.local"
  ingressClassName: traefik
  tls: false
  annotations: {}

replicaCount: 1

resources:
  requests: { cpu: 50m,  memory: 128Mi }
  limits:   { cpu: 200m, memory: 256Mi }

# WordPress -> init volumePermissions (os-shell) pin sur digest
volumePermissions:
  enabled: true
  image:
    registry: public.ecr.aws
    repository: bitnami/os-shell
    digest: "sha256:61080b8427911b6281815a4e03a36e056e3cccc49de211ad489547c4bdad651e"
    tag: ""   # vide pour éviter d'ajouter un tag

persistence:
  enabled: true
  storageClass: longhorn-1r
  size: 2Gi

metrics:
  enabled: false

mariadb:
  enabled: true
  architecture: standalone

  auth:
    database: "bitnami_wordpress"
    username: "bn_wordpress"
    password: "SbamwEzcqjSyBBQwg2?FKrz4"
    rootPassword: "TQdgiF#CW7AA!v@GSW%AWs?Z"

  primary:
    persistence:
      enabled: true
      storageClass: longhorn-1r
      size: 2Gi
    resources:
      requests: { cpu: 50m,  memory: 128Mi }
      limits:   { cpu: 200m, memory: 256Mi }

  metrics:
    enabled: false

  # MariaDB -> init volumePermissions (os-shell) pin sur digest
  volumePermissions:
    enabled: true
    image:
      registry: public.ecr.aws
      repository: bitnami/os-shell
      digest: "sha256:61080b8427911b6281815a4e03a36e056e3cccc49de211ad489547c4bdad651e"
      tag: ""   # vide pour éviter d'ajouter un tag

  allowEmptyPassword: false
  extraEnvVars:
    - name: ALLOW_EMPTY_PASSWORD
      value: "no"
