# wordpress/moi-sas/values.yaml
wordpressUsername: admin
wordpressPassword: "J9J!EJ#GW4C5QKwoXib#tA*A"
image:
  registry: docker.io
  repository: bitnami/wordpress
  tag: "latest"
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
ingress:
  enabled: true
  hostname: "moi.com.local"
  ingressClassName: traefik
  tls: false
  annotations: {}
replicaCount: 1
resources:
  requests: { cpu: 50m,  memory: 128Mi }
  limits:   { cpu: 200m, memory: 256Mi }
volumePermissions:
  enabled: true
  image:
    registry: docker.io
    repository: bitnami/os-shell
    tag: "12-debian-12-r30"
    pullPolicy: IfNotPresent
persistence:
  enabled: true
  storageClass: longhorn-1r
  size: 2Gi
mariadb:
  enabled: true
  architecture: standalone
  auth:
    database: "bitnami_wordpress"
    username: "bn_wordpress"
    password: "iFJpy2*euajmRGnUoN%ukf6!"
    rootPassword: "D5f%4PAXuKpXWHmgtpPQfFYy"
  primary:
    persistence:
      enabled: true
      storageClass: longhorn-1r
      size: 2Gi
    resources:
      requests: { cpu: 50m,  memory: 128Mi }
      limits:   { cpu: 200m, memory: 256Mi }
  metrics:
    enabled: false
  volumePermissions:
    enabled: true
    image:
      registry: docker.io
      repository: bitnami/os-shell
      tag: "12-debian-12-r30"
      pullPolicy: IfNotPresent
allowEmptyPassword: false
extraEnvVars:
  - name: ALLOW_EMPTY_PASSWORD
    value: "no"
metrics:
  enabled: false
