apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: wordpress-tenants
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/<YOU>/<REPO>.git
        revision: main
        directories:
          - path: Apps/wordpress/*          # <- un dossier = un client
  template:
    metadata:
      name: 'wp-{{path.basename}}'          # ex: wp-bremens-test
      labels:
        tenant: '{{path.basename}}'
        app.kubernetes.io/part-of: wordpress
    spec:
      project: default
      destination:
        server: https://kubernetes.default.svc
        namespace: 'wp-{{path.basename}}'   # ex: wp-bremens-test
      sources:
        # Source 1 : chart Bitnami
        - repoURL: https://charts.bitnami.com/bitnami
          chart: wordpress
          targetRevision: 19.2.0
          helm:
            valueFiles:
              - $values/Apps/wordpress/{{path.basename}}/values.yaml  # <- valeurs du client
        # Source 2 : ton repo (pour $values)
        - repoURL: https://github.com/<YOU>/<REPO>.git
          targetRevision: main
          ref: values
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
