wordpressUsername: admin
wordpressPassword: "__GENERE_PAR_N8N__"
ingress:
  enabled: true
  hostname: "blog.exemple.com"
  tls: true
  annotations:
    kubernetes.io/ingress.class: traefik
persistence:
  enabled: true
  storageClass: longhorn
  size: 2Gi
mariadb:
  primary:
    persistence:
      storageClass: longhorn
