# wordpress/bremens-sas/values.yaml
wordpressUsername: admin
wordpressPassword: "e7MQqrRmff%L2Ks8dmr!9eUX"
service:
  type: ClusterIP
ingress:
  enabled: true
  hostname: "bremens.com.local"
  ingressClassName: traefik
  tls: false
  annotations: {}
replicaCount: 1
resources:
  requests: { cpu: 50m,  memory: 128Mi }
  limits:   { cpu: 200m, memory: 256Mi }
volumePermissions:
  enabled: true
persistence:
  enabled: true
  storageClass: longhorn-1r
  size: 2Gi
mariadb:
  enabled: true
  architecture: standalone
  auth:
    database: "bitnami_wordpress"
    username: "bn_wordpress"
    password: "QbejNwi9rcXLBU9VfauNr8Uq"
    rootPassword: "ky32@2dmCYuKSV4Dm5t3CnH9"
  primary:
    persistence:
      enabled: true
      storageClass: longhorn-1r
      size: 2Gi
    resources:
      requests: { cpu: 50m,  memory: 128Mi }
      limits:   { cpu: 200m, memory: 256Mi }
  metrics:
    enabled: false
  volumePermissions:
    enabled: true
allowEmptyPassword: false
extraEnvVars:
  - name: ALLOW_EMPTY_PASSWORD
    value: "no"
metrics:
  enabled: false
